# Generated by Django 6.1.1 on 2026-09-07 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workloads', '0002_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='privacyconsent',
            old_name='allow_manager_alert',
            new_name='allow_hod_alerting',
        ),
        migrations.AlterField(
            model_name='privacyconsent',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_consent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('LECTURER', 'Lecturer / Academic Staff'), ('HOD', 'Head of Department / Dean'), ('ADMIN_STAFF', 'Administrative Officer (HR, Finance, Procurement)'), ('HR_MANAGER', 'HR Manager / Governance'), ('SYSTEM_ADMIN', 'System Administrator')], default='LECTURER', max_length=20),
        ),
    ]
