# Generated by Django 6.1.1 on 2026-09-08 09:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workloads', '0003_rename_allow_manager_alert_privacyconsent_allow_hod_alerting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='academic_rank',
            field=models.CharField(choices=[('TUTOR', 'Tutorial Assistant'), ('LECTURER', 'Lecturer'), ('SENIOR_LECTURER', 'Senior Lecturer'), ('ASSOC_PROF', 'Associate Professor'), ('PROFESSOR', 'Professor')], default='LECTURER', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='active_student_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='contractual_max_hours',
            field=models.FloatField(default=20.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='grading_backlog_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='workloadlog',
            name='burnout_risk_score',
            field=models.FloatField(default=0.0, help_text='BRS 0-100%', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AddField(
            model_name='workloadlog',
            name='lms_off_hours_activity',
            field=models.FloatField(default=0.0, help_text='Hours logged on LMS between 8 PM and 6 AM or weekends.'),
        ),
        migrations.AddField(
            model_name='workloadlog',
            name='module_prep_hours',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('LECTURER', 'Lecturer / Academic Staff'), ('HOD', 'Head of Department / Dean'), ('ADMIN_STAFF', 'Administrative Officer'), ('HR_MANAGER', 'HR Manager / Governance'), ('SYSTEM_ADMIN', 'System Administrator')], default='LECTURER', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(choices=[('BIT', 'Business Information Technology'), ('HTM', 'Hospitality & Tourism Management'), ('BA', 'Business Administration'), ('ADM', 'Central Administration')], default='BIT', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('LECTURER', 'Lecturer / Academic Staff'), ('HOD', 'Head of Department / Dean'), ('ADMIN_STAFF', 'Administrative Officer'), ('HR_MANAGER', 'HR Manager / Governance'), ('SYSTEM_ADMIN', 'System Administrator')], default='LECTURER', max_length=20),
        ),
        migrations.CreateModel(
            name='AssistanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('FATIGUE', 'Fatigue / Mental Health Flag'), ('MARKING_SUPPORT', 'Marking / Grading Assistant Request'), ('LEAVE', 'Short-term Workload Adjustment / Leave')], max_length=20)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Declined')], default='PENDING', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistance_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskReallocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_description', models.CharField(max_length=255)),
                ('hours_reallocated', models.FloatField(validators=[django.core.validators.MinValueValidator(0.5)])),
                ('status', models.CharField(choices=[('SUGGESTED', 'AI Suggested'), ('ACCEPTED', 'Accepted'), ('MODIFIED', 'Modified'), ('REJECTED', 'Overridden / Rejected')], default='SUGGESTED', max_length=15)),
                ('hod_comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reallocations_out', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reallocations_in', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
